package com.opentest.test.main;

public class BlockFinallyReturn {
	
	
	/**
	 * to chekcing, 
	 * - `return` in try block finally block executes, 
	 * - (1) `return` available in both try, finally block, what happens to chekcing, 
	 *   >> above tried, finally block's `return` value returns, of above scenario 
	 *  
	 * @return
	 * @throws Exception
	 */
	public int checkFinallyBlockFromReturns() throws Exception {
		
		try {
			System.out.println("Inside try block <> 00000");
			
			return 0;
		} catch(Exception e) {
			//System.out.println("Exception in checkFinallyBlockFromReturns: "+e.getMessage());
			//e.printStackTrace();
			throw e;
		} finally {
			System.out.println("Inside finally block <> 111111");
			//return 1;	// (1)
		}
	}
	
	
	public static void main(String[] args) {
		BlockFinallyReturn blockFinallyReturn = null;
		
		int nRtn = -1;
		
		try {
			System.out.println("Inside main");
			
			blockFinallyReturn = new BlockFinallyReturn();
			
			nRtn = blockFinallyReturn.checkFinallyBlockFromReturns();
			
			System.out.println("nRtn: "+nRtn);
			
			blockFinallyReturn = null;
		} catch(Exception e) {
			System.out.println("Exception in main: "+e.getMessage());
			e.printStackTrace();
		} finally {
			
		}
	}
}
